/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ThemeColor from '../theme/color.defs.js'

const $nsid = 'pub.leaflet.richtext.facet'

export { $nsid }

/** Facet feature for an identifier. Used for linking to a segment */
type Id = { $type?: 'pub.leaflet.richtext.facet#id'; id?: string }

export type { Id }

/** Facet feature for an identifier. Used for linking to a segment */
const id = l.typedObject<Id>(
  $nsid,
  'id',
  l.object({ id: l.optional(l.string()) }),
)

export { id }

/** Facet feature for bold text */
type Bold = { $type?: 'pub.leaflet.richtext.facet#bold' }

export type { Bold }

/** Facet feature for bold text */
const bold = l.typedObject<Bold>($nsid, 'bold', l.object({}))

export { bold }

/** Facet feature for inline code. */
type Code = { $type?: 'pub.leaflet.richtext.facet#code' }

export type { Code }

/** Facet feature for inline code. */
const code = l.typedObject<Code>($nsid, 'code', l.object({}))

export { code }

/** Facet feature for a URL. The text URL may have been simplified or truncated, but the facet reference should be a complete URL. */
type Link = { $type?: 'pub.leaflet.richtext.facet#link'; uri: string }

export type { Link }

/** Facet feature for a URL. The text URL may have been simplified or truncated, but the facet reference should be a complete URL. */
const link = l.typedObject<Link>($nsid, 'link', l.object({ uri: l.string() }))

export { link }

/** Annotation of a sub-string within rich text. */
type Main = {
  $type?: 'pub.leaflet.richtext.facet'
  index: ByteSlice
  features: (
    | l.$Typed<Link>
    | l.$Typed<DidMention>
    | l.$Typed<AtMention>
    | l.$Typed<Code>
    | l.$Typed<Highlight>
    | l.$Typed<Underline>
    | l.$Typed<Strikethrough>
    | l.$Typed<Id>
    | l.$Typed<Bold>
    | l.$Typed<Italic>
    | l.$Typed<Footnote>
    | l.Unknown$TypedObject
  )[]
}

export type { Main }

/** Annotation of a sub-string within rich text. */
const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    index: l.ref<ByteSlice>((() => byteSlice) as any),
    features: l.array(
      l.typedUnion(
        [
          l.typedRef<Link>((() => link) as any),
          l.typedRef<DidMention>((() => didMention) as any),
          l.typedRef<AtMention>((() => atMention) as any),
          l.typedRef<Code>((() => code) as any),
          l.typedRef<Highlight>((() => highlight) as any),
          l.typedRef<Underline>((() => underline) as any),
          l.typedRef<Strikethrough>((() => strikethrough) as any),
          l.typedRef<Id>((() => id) as any),
          l.typedRef<Bold>((() => bold) as any),
          l.typedRef<Italic>((() => italic) as any),
          l.typedRef<Footnote>((() => footnote) as any),
        ],
        false,
      ),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Facet feature for italic text */
type Italic = { $type?: 'pub.leaflet.richtext.facet#italic' }

export type { Italic }

/** Facet feature for italic text */
const italic = l.typedObject<Italic>($nsid, 'italic', l.object({}))

export { italic }

/** Facet feature for a footnote reference */
type Footnote = {
  $type?: 'pub.leaflet.richtext.facet#footnote'
  footnoteId: string
  contentFacets?: Main[]
  contentPlaintext: string
}

export type { Footnote }

/** Facet feature for a footnote reference */
const footnote = l.typedObject<Footnote>(
  $nsid,
  'footnote',
  l.object({
    footnoteId: l.string(),
    contentFacets: l.optional(l.array(l.ref<Main>((() => main) as any))),
    contentPlaintext: l.string(),
  }),
)

export { footnote }

/** Facet feature for mentioning an AT URI. */
type AtMention = {
  $type?: 'pub.leaflet.richtext.facet#atMention'
  href?: l.UriString
  atURI: l.UriString
}

export type { AtMention }

/** Facet feature for mentioning an AT URI. */
const atMention = l.typedObject<AtMention>(
  $nsid,
  'atMention',
  l.object({
    href: l.optional(l.string({ format: 'uri' })),
    atURI: l.string({ format: 'uri' }),
  }),
)

export { atMention }

/** Specifies the sub-string range a facet feature applies to. Start index is inclusive, end index is exclusive. Indices are zero-indexed, counting bytes of the UTF-8 encoded text. NOTE: some languages, like Javascript, use UTF-16 or Unicode codepoints for string slice indexing; in these languages, convert to byte arrays before working with facets. */
type ByteSlice = {
  $type?: 'pub.leaflet.richtext.facet#byteSlice'
  byteEnd: number
  byteStart: number
}

export type { ByteSlice }

/** Specifies the sub-string range a facet feature applies to. Start index is inclusive, end index is exclusive. Indices are zero-indexed, counting bytes of the UTF-8 encoded text. NOTE: some languages, like Javascript, use UTF-16 or Unicode codepoints for string slice indexing; in these languages, convert to byte arrays before working with facets. */
const byteSlice = l.typedObject<ByteSlice>(
  $nsid,
  'byteSlice',
  l.object({
    byteEnd: l.integer({ minimum: 0 }),
    byteStart: l.integer({ minimum: 0 }),
  }),
)

export { byteSlice }

/** Facet feature for highlighted text. */
type Highlight = {
  $type?: 'pub.leaflet.richtext.facet#highlight'
  color?:
    | l.$Typed<ThemeColor.Rgba>
    | l.$Typed<ThemeColor.Rgb>
    | l.Unknown$TypedObject
}

export type { Highlight }

/** Facet feature for highlighted text. */
const highlight = l.typedObject<Highlight>(
  $nsid,
  'highlight',
  l.object({
    color: l.optional(
      l.typedUnion(
        [
          l.typedRef<ThemeColor.Rgba>((() => ThemeColor.rgba) as any),
          l.typedRef<ThemeColor.Rgb>((() => ThemeColor.rgb) as any),
        ],
        false,
      ),
    ),
  }),
)

export { highlight }

/** Facet feature for underline markup */
type Underline = { $type?: 'pub.leaflet.richtext.facet#underline' }

export type { Underline }

/** Facet feature for underline markup */
const underline = l.typedObject<Underline>($nsid, 'underline', l.object({}))

export { underline }

/** Facet feature for mentioning a did. */
type DidMention = {
  $type?: 'pub.leaflet.richtext.facet#didMention'
  did: l.DidString
}

export type { DidMention }

/** Facet feature for mentioning a did. */
const didMention = l.typedObject<DidMention>(
  $nsid,
  'didMention',
  l.object({ did: l.string({ format: 'did' }) }),
)

export { didMention }

/** Facet feature for strikethrough markup */
type Strikethrough = { $type?: 'pub.leaflet.richtext.facet#strikethrough' }

export type { Strikethrough }

/** Facet feature for strikethrough markup */
const strikethrough = l.typedObject<Strikethrough>(
  $nsid,
  'strikethrough',
  l.object({}),
)

export { strikethrough }
