/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'id.sifa.profile.language'

export { $nsid }

/** Record representing a single language proficiency. */
type Main = {
  $type: 'id.sifa.profile.language'

  /**
   * Language name (e.g., 'English', 'Nederlands', 'Deutsch').
   */
  name: string

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString

  /**
   * Proficiency level. Uses LinkedIn-compatible five-level scale.
   */
  proficiency?:
    | 'id.sifa.defs#elementary'
    | 'id.sifa.defs#limitedWorking'
    | 'id.sifa.defs#professionalWorking'
    | 'id.sifa.defs#fullProfessional'
    | 'id.sifa.defs#native'
    | l.UnknownString
}

export type { Main }

/** Record representing a single language proficiency. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    name: l.string({ maxLength: 640, minLength: 1, maxGraphemes: 64 }),
    createdAt: l.string({ format: 'datetime' }),
    proficiency: l.optional(
      l.string<{
        knownValues: [
          'id.sifa.defs#elementary',
          'id.sifa.defs#limitedWorking',
          'id.sifa.defs#professionalWorking',
          'id.sifa.defs#fullProfessional',
          'id.sifa.defs#native',
        ]
      }>(),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
