/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as LabelDefs from '../../com/atproto/label/defs.defs.js'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.js'

const $nsid = 'site.standard.document'

export { $nsid }

/** A document record representing a published article, blog post, or other content. Documents can belong to a publication or exist independently. */
type Main = {
  $type: 'site.standard.document'

  /**
   * Combine with site or publication url to construct a canonical URL to the document. Prepend with a leading slash.
   */
  path?: string

  /**
   * Points to a publication record (at://) or a publication url (https://) for loose documents. Avoid trailing slashes.
   */
  site: l.UriString

  /**
   * Array of strings used to tag or categorize the document. Avoid prepending tags with hashtags.
   */
  tags?: string[]

  /**
   * Array of values describing relationships between this document and external resources
   */
  links?: l.Unknown$TypedObject

  /**
   * Title of the document.
   */
  title: string

  /**
   * Self-label values for this post. Effectively content warnings.
   */
  labels?: l.$Typed<LabelDefs.SelfLabels> | l.Unknown$TypedObject

  /**
   * Open union used to define the record's content. Each entry must specify a $type and may be extended with other lexicons to support additional content formats.
   */
  content?: l.Unknown$TypedObject

  /**
   * Timestamp of the documents last edit.
   */
  updatedAt?: l.DatetimeString

  /**
   * Image to used for thumbnail or cover image. Less than 1MB is size.
   */
  coverImage?: l.BlobRef

  /**
   * Strong reference to a Bluesky post. Useful to keep track of comments off-platform.
   */
  bskyPostRef?: RepoStrongRef.Main

  /**
   * A brief description or excerpt from the document.
   */
  description?: string

  /**
   * Timestamp of the documents publish time.
   */
  publishedAt: l.DatetimeString

  /**
   * Plaintext representation of the documents contents. Should not contain markdown or other formatting.
   */
  textContent?: string
  contributors?: Contributor[]
}

export type { Main }

/** A document record representing a published article, blog post, or other content. Documents can belong to a publication or exist independently. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    path: l.optional(l.string()),
    site: l.string({ format: 'uri' }),
    tags: l.optional(l.array(l.string({ maxLength: 1280, maxGraphemes: 128 }))),
    links: l.optional(l.typedUnion([], false)),
    title: l.string({ maxLength: 5000, maxGraphemes: 500 }),
    labels: l.optional(
      l.typedUnion(
        [l.typedRef<LabelDefs.SelfLabels>((() => LabelDefs.selfLabels) as any)],
        false,
      ),
    ),
    content: l.optional(l.typedUnion([], false)),
    updatedAt: l.optional(l.string({ format: 'datetime' })),
    coverImage: l.optional(l.blob({ accept: ['image/*'], maxSize: 1000000 })),
    bskyPostRef: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    description: l.optional(l.string({ maxLength: 30000, maxGraphemes: 3000 })),
    publishedAt: l.string({ format: 'datetime' }),
    textContent: l.optional(l.string()),
    contributors: l.optional(
      l.array(l.ref<Contributor>((() => contributor) as any)),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Contributor = {
  $type?: 'site.standard.document#contributor'
  did: l.DidString
  role?: string
  displayName?: string
}

export type { Contributor }

const contributor = l.typedObject<Contributor>(
  $nsid,
  'contributor',
  l.object({
    did: l.string({ format: 'did' }),
    role: l.optional(l.string({ maxLength: 1000, maxGraphemes: 100 })),
    displayName: l.optional(l.string({ maxLength: 1000, maxGraphemes: 100 })),
  }),
)

export { contributor }
