services:
  caddy:
    container_name: caddy
    image: caddy:2
    network_mode: host
    depends_on:
      - eurosky-portal
    restart: unless-stopped
    volumes:
      - type: bind
        source: /portal-app/caddy/data
        target: /data
      - type: bind
        source: /portal-app/caddy/etc/caddy
        target: /etc/caddy
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  eurosky-portal:
    container_name: eurosky-portal
    image: ghcr.io/eurosky-social/eurosky-portal:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: /portal-app/db
        target: /data
    env_file:
      - /portal-app/app.env
    network_mode: host
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL',"curl -s --noproxy localhost localhost:4075/health | grep -q 'OK' || exit 1"]
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  watchtower:
    container_name: watchtower
    # we're using a fork of watchtower, as containrrr/watchtower hasn't been
    # updated in 2 years and is incompatible with latest docker on debian:
    image: nickfedor/watchtower:latest
    network_mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: '@midnight'
      WATCHTOWER_LABEL_ENABLE: true
