/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Account: () => import('#controllers/account_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Explore: () => import('#controllers/explore_controller'),
  Faq: () => import('#controllers/faq_controller'),
  Home: () => import('#controllers/home_controller'),
  Legal: () => import('#controllers/legal_controller'),
  Oauth: () => import('#controllers/oauth_controller'),
}
