/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import type { l } from '@atproto/lex'

export class AccountSchema extends BaseModel {
  static $columns = ['createdAt', 'did', 'handle', 'lastActiveAt', 'lastActivitySyncAt', 'termsAcceptedAt', 'updatedAt', 'welcomeDismissed'] as const
  $columns = AccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare did: l.DidString
  @column()
  declare handle: l.HandleString | null
  @column.dateTime()
  declare lastActiveAt: DateTime | null
  @column.dateTime()
  declare lastActivitySyncAt: DateTime | null
  @column.dateTime()
  declare termsAcceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ consume: (value) => !!value })
  declare welcomeDismissed: boolean | null
}

export class ActivityRecordSchema extends BaseModel {
  static $columns = ['cid', 'collection', 'createdAt', 'did', 'indexedAt', 'rkey', 'text', 'uri'] as const
  $columns = ActivityRecordSchema.$columns
  @column()
  declare cid: string
  @column()
  declare collection: string
  @column.dateTime()
  declare createdAt: DateTime | null
  @column()
  declare did: l.DidString
  @column.dateTime()
  declare indexedAt: DateTime
  @column()
  declare rkey: string
  @column()
  declare text: string | null
  @column({ isPrimary: true })
  declare uri: string
}

export class CacheSchema extends BaseModel {
  static $columns = ['expiresAt', 'key', 'value'] as const
  $columns = CacheSchema.$columns
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare value: string | null
}

export class OauthSessionSchema extends BaseModel {
  static $columns = ['sub', 'updatedAt', 'value'] as const
  $columns = OauthSessionSchema.$columns
  @column({ isPrimary: true })
  declare sub: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}

export class OauthStateSchema extends BaseModel {
  static $columns = ['key', 'updatedAt', 'value'] as const
  $columns = OauthStateSchema.$columns
  @column({ isPrimary: true })
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}
