/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/atproto_oauth.ts" />
/// <reference path="../../config/auth.ts" />
/// <reference path="../../config/cache.ts" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/logger.ts" />
/// <reference path="../../config/monocle.ts" />
/// <reference path="../../config/queue.ts" />
