/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fyi.atstore.directory.getListing'

export { $nsid }

/** Fetch one public verified listing. Provide exactly one of `uri` (fyi.atstore.listing.detail AT URI) or `externalUrl` (unique storefront URL); `externalUrl` uses the same matching rules as the former resolve endpoint. */
const main = l.query(
  $nsid,
  l.params({
    uri: l.optional(l.string({ format: 'at-uri', maxLength: 2560 })),
    externalUrl: l.optional(l.string({ maxLength: 2048 })),
  }),
  l.payload(
    'application/json',
    l.ref<ListingDetailResponse>((() => listingDetailResponse) as any),
  ),
  ['ListingNotFound', 'InvalidParams', 'AmbiguousResolution'],
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type ListingCardGet = {
  $type?: 'fyi.atstore.directory.getListing#listingCardGet'

  /**
   * AT URI of the fyi.atstore.listing.detail record.
   */
  uri: l.AtUriString
  name: string
  accent: 'blue' | 'pink' | 'purple' | 'green' | l.UnknownString
  rating?: string
  appTags: string[]
  iconUrl?: string
  tagline: string
  category: string
  priceLabel: string
  description: string
  reviewCount: number
  categorySlug?: string
  heroImageUrl?: string
  categorySlugs: string[]
  productAccountHandle?: string
}

export type { ListingCardGet }

const listingCardGet = l.typedObject<ListingCardGet>(
  $nsid,
  'listingCardGet',
  l.object({
    uri: l.string({ format: 'at-uri', maxLength: 2560 }),
    name: l.string({ maxLength: 640 }),
    accent: l.string<{
      maxLength: 16
      knownValues: ['blue', 'pink', 'purple', 'green']
    }>({ maxLength: 16 }),
    rating: l.optional(l.string({ maxLength: 16 })),
    appTags: l.array(l.string({ maxLength: 256 })),
    iconUrl: l.optional(l.string({ maxLength: 8192 })),
    tagline: l.string({ maxLength: 2000 }),
    category: l.string({ maxLength: 640 }),
    priceLabel: l.string({ maxLength: 32 }),
    description: l.string({ maxLength: 20000 }),
    reviewCount: l.integer(),
    categorySlug: l.optional(l.string({ maxLength: 512 })),
    heroImageUrl: l.optional(l.string({ maxLength: 8192 })),
    categorySlugs: l.array(l.string({ maxLength: 512 })),
    productAccountHandle: l.optional(l.string({ maxLength: 512 })),
  }),
)

export { listingCardGet }

type ListingLinkRow = {
  $type?: 'fyi.atstore.directory.getListing#listingLinkRow'
  uri: string
  label?: string
}

export type { ListingLinkRow }

const listingLinkRow = l.typedObject<ListingLinkRow>(
  $nsid,
  'listingLinkRow',
  l.object({
    uri: l.string({ maxLength: 2048 }),
    label: l.optional(l.string({ maxLength: 640 })),
  }),
)

export { listingLinkRow }

type ListingDetailResponse = {
  $type?: 'fyi.atstore.directory.getListing#listingDetailResponse'
  links?: ListingLinkRow[]
  listing: ListingCardGet
  repoDid?: string
  createdAt?: string
  sourceUrl?: string
  updatedAt?: string
  externalUrl?: string
  screenshots?: string[]
  sourceTagline?: string
  isStoreManaged: boolean
  productAccountDid?: string
  sourceFullDescription?: string
}

export type { ListingDetailResponse }

const listingDetailResponse = l.typedObject<ListingDetailResponse>(
  $nsid,
  'listingDetailResponse',
  l.object({
    links: l.optional(
      l.array(l.ref<ListingLinkRow>((() => listingLinkRow) as any)),
    ),
    listing: l.ref<ListingCardGet>((() => listingCardGet) as any),
    repoDid: l.optional(l.string({ maxLength: 2048 })),
    createdAt: l.optional(l.string({ maxLength: 64 })),
    sourceUrl: l.optional(l.string({ maxLength: 8192 })),
    updatedAt: l.optional(l.string({ maxLength: 64 })),
    externalUrl: l.optional(l.string({ maxLength: 2048 })),
    screenshots: l.optional(l.array(l.string({ maxLength: 4096 }))),
    sourceTagline: l.optional(l.string({ maxLength: 20000 })),
    isStoreManaged: l.boolean(),
    productAccountDid: l.optional(l.string({ maxLength: 2048 })),
    sourceFullDescription: l.optional(l.string({ maxLength: 20000 })),
  }),
)

export { listingDetailResponse }
