/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'social.eurosky.portal.sync.getStorageBreakdown'

export { $nsid }

/** Get aggregated storage totals for an account grouped by coarse blob category. */
const main = l.query(
  $nsid,
  l.params({ did: l.string({ format: 'did' }) }),
  l.jsonPayload({
    categories: l.array(l.ref<Category>((() => category) as any)),
    did: l.string({ format: 'did' }),
    generatedAt: l.string({ format: 'datetime' }),
    totalBytes: l.integer({ minimum: 0 }),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type Category = {
  $type?: 'social.eurosky.portal.sync.getStorageBreakdown#category'
  bytes: number
  files: number
  category: 'image' | 'other' | 'video' | l.UnknownString
}

export type { Category }

const category = l.typedObject<Category>(
  $nsid,
  'category',
  l.object({
    bytes: l.integer({ minimum: 0 }),
    files: l.integer({ minimum: 0 }),
    category: l.string<{ knownValues: ['image', 'other', 'video'] }>(),
  }),
)

export { category }
