/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'social.eurosky.portal.sync.listBlobDetails'

export { $nsid }

/** List blob metadata for an account, including CID, mime type, size, and creation timestamp. Supports optional category filtering. */
const main = l.query(
  $nsid,
  l.params({
    category: l.optional(
      l.string<{ knownValues: ['image', 'other', 'video'] }>(),
    ),
    cursor: l.optional(l.string()),
    did: l.string({ format: 'did' }),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 1000 }), 500),
    ),
  }),
  l.jsonPayload({
    blobs: l.array(l.ref<Blob>((() => blob) as any)),
    cursor: l.optional(l.string()),
    did: l.string({ format: 'did' }),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type Blob = {
  $type?: 'social.eurosky.portal.sync.listBlobDetails#blob'
  cid: l.CidString
  createdAt: l.DatetimeString
  mimeType?: string
  size: number
}

export type { Blob }

const blob = l.typedObject<Blob>(
  $nsid,
  'blob',
  l.object({
    cid: l.string({ format: 'cid' }),
    createdAt: l.string({ format: 'datetime' }),
    mimeType: l.optional(l.string()),
    size: l.integer({ minimum: 0 }),
  }),
)

export { blob }
