/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as PagesLinearDocument from './pages/linearDocument.defs.js'
import * as PagesCanvas from './pages/canvas.defs.js'

const $nsid = 'pub.leaflet.content'

export { $nsid }

/** Content format for leaflet documents */
type Main = {
  $type?: 'pub.leaflet.content'

  /**
   * Blobs referenced inside `blobPages`. Load-bearing when `blobPages` is set: the PDS only scans the top level of a record for blob references when deciding what to garbage-collect, so any image/etc. blob now living inside the opaque JSON blob must be mirrored here to remain referenced.
   */
  blobs?: l.BlobRef[]
  pages: (
    | l.$Typed<PagesLinearDocument.Main>
    | l.$Typed<PagesCanvas.Main>
    | l.Unknown$TypedObject
  )[]

  /**
   * JSON-encoded array of pages. When the inline pages array would be too large to store on the PDS, the pages are uploaded as a blob and referenced here. When set, consumers MUST ignore `pages` and use the decoded blob contents as the page array; the inline `pages` field will be empty or a stub.
   */
  blobPages?: l.BlobRef
}

export type { Main }

/** Content format for leaflet documents */
const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    blobs: l.optional(l.array(l.blob({ accept: ['*/*'], maxSize: 10000000 }))),
    pages: l.array(
      l.typedUnion(
        [
          l.typedRef<PagesLinearDocument.Main>(
            (() => PagesLinearDocument.main) as any,
          ),
          l.typedRef<PagesCanvas.Main>((() => PagesCanvas.main) as any),
        ],
        false,
      ),
    ),
    blobPages: l.optional(
      l.blob({ accept: ['application/json'], maxSize: 5000000 }),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
