/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'pub.leaflet.blocks.imageGallery'

export { $nsid }

type Main = {
  $type?: 'pub.leaflet.blocks.imageGallery'

  /**
   * Gap between images in pixels.
   */
  gap?: number
  format?: 'grid' | 'carousel' | 'strip' | l.UnknownString
  images: Image[]

  /**
   * Max width per image in grid view (px); drives how many columns fit.
   */
  maxWidth?: number
}

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    gap: l.optional(l.integer()),
    format: l.optional(
      l.string<{ knownValues: ['grid', 'carousel', 'strip'] }>(),
    ),
    images: l.array(l.ref<Image>((() => image) as any)),
    maxWidth: l.optional(l.integer()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Image = {
  $type?: 'pub.leaflet.blocks.imageGallery#image'

  /**
   * Alt text description of the image, for accessibility.
   */
  alt?: string
  image: l.BlobRef
  aspectRatio: AspectRatio
}

export type { Image }

const image = l.typedObject<Image>(
  $nsid,
  'image',
  l.object({
    alt: l.optional(l.string()),
    image: l.blob({ accept: ['image/*'], maxSize: 1000000 }),
    aspectRatio: l.ref<AspectRatio>((() => aspectRatio) as any),
  }),
)

export { image }

type AspectRatio = {
  $type?: 'pub.leaflet.blocks.imageGallery#aspectRatio'
  width: number
  height: number
}

export type { AspectRatio }

const aspectRatio = l.typedObject<AspectRatio>(
  $nsid,
  'aspectRatio',
  l.object({ width: l.integer(), height: l.integer() }),
)

export { aspectRatio }
