/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'pub.leaflet.blocks.standardSitePost'

export { $nsid }

type Main = {
  $type?: 'pub.leaflet.blocks.standardSitePost'
  cid?: string
  uri: l.AtUriString
  size?: 'large' | 'medium' | 'small' | l.UnknownString
  showPublicationTheme?: boolean
}

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    cid: l.optional(l.string()),
    uri: l.string({ format: 'at-uri' }),
    size: l.optional(l.string<{ knownValues: ['large', 'medium', 'small'] }>()),
    showPublicationTheme: l.optional(l.boolean()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
