/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as BlocksText from './text.defs.js'
import * as BlocksHeader from './header.defs.js'
import * as BlocksImage from './image.defs.js'
import * as BlocksOrderedList from './orderedList.defs.js'

const $nsid = 'pub.leaflet.blocks.unorderedList'

export { $nsid }

type Main = { $type?: 'pub.leaflet.blocks.unorderedList'; children: ListItem[] }

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({ children: l.array(l.ref<ListItem>((() => listItem) as any)) }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type ListItem = {
  $type?: 'pub.leaflet.blocks.unorderedList#listItem'

  /**
   * If present, this item is a checklist item. true = checked, false = unchecked. If absent, this is a normal list item.
   */
  checked?: boolean
  content:
    | l.$Typed<BlocksText.Main>
    | l.$Typed<BlocksHeader.Main>
    | l.$Typed<BlocksImage.Main>
    | l.Unknown$TypedObject

  /**
   * Nested unordered list items. Mutually exclusive with orderedListChildren; if both are present, children takes precedence.
   */
  children?: ListItem[]

  /**
   * Nested ordered list items. Mutually exclusive with children; if both are present, children takes precedence.
   */
  orderedListChildren?: BlocksOrderedList.Main
}

export type { ListItem }

const listItem = l.typedObject<ListItem>(
  $nsid,
  'listItem',
  l.object({
    checked: l.optional(l.boolean()),
    content: l.typedUnion(
      [
        l.typedRef<BlocksText.Main>((() => BlocksText.main) as any),
        l.typedRef<BlocksHeader.Main>((() => BlocksHeader.main) as any),
        l.typedRef<BlocksImage.Main>((() => BlocksImage.main) as any),
      ],
      false,
    ),
    children: l.optional(l.array(l.ref<ListItem>((() => listItem) as any))),
    orderedListChildren: l.optional(
      l.ref<BlocksOrderedList.Main>((() => BlocksOrderedList.main) as any),
    ),
  }),
)

export { listItem }
