/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'id.sifa.defs'

export { $nsid }

/** Hosted or moderated the session. */
type Host = 'id.sifa.defs#host'

export type { Host }

/** Hosted or moderated the session. */
const host = l.token($nsid, 'host')

export { host }

/** Hybrid on-site and remote work. */
type Hybrid = 'id.sifa.defs#hybrid'

export type { Hybrid }

/** Hybrid on-site and remote work. */
const hybrid = l.token($nsid, 'hybrid')

export { hybrid }

/** Native or bilingual proficiency. */
type Native$0 = 'id.sifa.defs#native'

export type { Native$0 as Native }

/** Native or bilingual proficiency. */
const native$0 = l.token($nsid, 'native')

export { native$0 as 'native' }

/** On-site/in-office work. */
type OnSite = 'id.sifa.defs#onSite'

export type { OnSite }

/** On-site/in-office work. */
const onSite = l.token($nsid, 'onSite')

export { onSite }

/** Fully remote work (unspecified scope). Treated as remoteGlobal by AppViews. Prefer the scoped variants for new records. */
type Remote = 'id.sifa.defs#remote'

export type { Remote }

/** Fully remote work (unspecified scope). Treated as remoteGlobal by AppViews. Prefer the scoped variants for new records. */
const remote = l.token($nsid, 'remote')

export { remote }

/** Gave a keynote address. */
type Keynote = 'id.sifa.defs#keynote'

export type { Keynote }

/** Gave a keynote address. */
const keynote = l.token($nsid, 'keynote')

export { keynote }

/** Structured early-career rotation or graduate program. */
type Trainee = 'id.sifa.defs#trainee'

export type { Trainee }

/** Structured early-career rotation or graduate program. */
const trainee = l.token($nsid, 'trainee')

export { trainee }

/** Business and management skills. */
type Business = 'id.sifa.defs#business'

export type { Business }

/** Business and management skills. */
const business = l.token($nsid, 'business')

export { business }

/** Fixed-scope engagement as an independent contractor. */
type Contract = 'id.sifa.defs#contract'

export type { Contract }

/** Fixed-scope engagement as an independent contractor. */
const contract = l.token($nsid, 'contract')

export { contract }

/** Creative and design skills. */
type Creative = 'id.sifa.defs#creative'

export type { Creative }

/** Creative and design skills. */
const creative = l.token($nsid, 'creative')

export { creative }

/** Full-time employee of the organization. */
type FullTime = 'id.sifa.defs#fullTime'

export type { FullTime }

/** Full-time employee of the organization. */
const fullTime = l.token($nsid, 'fullTime')

export { fullTime }

/** Industry-specific domain knowledge. */
type Industry = 'id.sifa.defs#industry'

export type { Industry }

/** Industry-specific domain knowledge. */
const industry = l.token($nsid, 'industry')

export { industry }

/** Language and linguistic skills. */
type Language = 'id.sifa.defs#language'

export type { Language }

/** Language and linguistic skills. */
const language = l.token($nsid, 'language')

export { language }

/** Participated as a member of a panel. */
type Panelist = 'id.sifa.defs#panelist'

export type { Panelist }

/** Participated as a member of a panel. */
const panelist = l.token($nsid, 'panelist')

export { panelist }

/** Part-time employee of the organization. */
type PartTime = 'id.sifa.defs#partTime'

export type { PartTime }

/** Part-time employee of the organization. */
const partTime = l.token($nsid, 'partTime')

export { partTime }

/** Recurring role tied to a season or peak period. */
type Seasonal = 'id.sifa.defs#seasonal'

export type { Seasonal }

/** Recurring role tied to a season or peak period. */
const seasonal = l.token($nsid, 'seasonal')

export { seasonal }

/** A reference to an id.sifa.profile.skill record by AT-URI. No CID is required because skills are mutable records in the same user's repo. */
type SkillRef = {
  $type?: 'id.sifa.defs#skillRef'

  /**
   * AT-URI of the id.sifa.profile.skill record.
   */
  uri: l.AtUriString
}

export type { SkillRef }

/** A reference to an id.sifa.profile.skill record by AT-URI. No CID is required because skills are mutable records in the same user's repo. */
const skillRef = l.typedObject<SkillRef>(
  $nsid,
  'skillRef',
  l.object({ uri: l.string({ format: 'at-uri' }) }),
)

export { skillRef }

/** Led or facilitated a workshop or tutorial. */
type Workshop = 'id.sifa.defs#workshop'

export type { Workshop }

/** Led or facilitated a workshop or tutorial. */
const workshop = l.token($nsid, 'workshop')

export { workshop }

/** Solo service provider working with multiple clients on a project basis. No employees. */
type Freelance = 'id.sifa.defs#freelance'

export type { Freelance }

/** Solo service provider working with multiple clients on a project basis. No employees. */
const freelance = l.token($nsid, 'freelance')

export { freelance }

/** The event or session page. */
type LinkEvent = 'id.sifa.defs#linkEvent'

export type { LinkEvent }

/** The event or session page. */
const linkEvent = l.token($nsid, 'linkEvent')

export { linkEvent }

/** Other related link. */
type LinkOther = 'id.sifa.defs#linkOther'

export type { LinkOther }

/** Other related link. */
const linkOther = l.token($nsid, 'linkOther')

export { linkOther }

/** Delivered the session as the speaker or presenter (spoken or non-spoken). */
type Presenter = 'id.sifa.defs#presenter'

export type { Presenter }

/** Delivered the session as the speaker or presenter (spoken or non-spoken). */
const presenter = l.token($nsid, 'presenter')

export { presenter }

/** Technical/engineering skills. */
type Technical = 'id.sifa.defs#technical'

export type { Technical }

/** Technical/engineering skills. */
const technical = l.token($nsid, 'technical')

export { technical }

/** Fixed-end-date role as a direct employee of the organization. */
type Temporary = 'id.sifa.defs#temporary'

export type { Temporary }

/** Fixed-end-date role as a direct employee of the organization. */
const temporary = l.token($nsid, 'temporary')

export { temporary }

/** Volunteer work (when used as employment type). */
type Volunteer = 'id.sifa.defs#volunteer'

export type { Volunteer }

/** Volunteer work (when used as employment type). */
const volunteer = l.token($nsid, 'volunteer')

export { volunteer }

/** Professional domain within an industry. Optional refinement of industryType. */
type DomainType =
  | 'id.sifa.defs#domainSoftwareEngineering'
  | 'id.sifa.defs#domainDataScience'
  | 'id.sifa.defs#domainCybersecurity'
  | 'id.sifa.defs#domainDevops'
  | 'id.sifa.defs#domainProductDesign'
  | 'id.sifa.defs#domainGameDev'
  | 'id.sifa.defs#domainBanking'
  | 'id.sifa.defs#domainFintech'
  | 'id.sifa.defs#domainInsurance'
  | 'id.sifa.defs#domainInvestmentMgmt'
  | 'id.sifa.defs#domainClinicalResearch'
  | 'id.sifa.defs#domainHealthtech'
  | 'id.sifa.defs#domainPharma'
  | 'id.sifa.defs#domainHigherEd'
  | 'id.sifa.defs#domainEdtech'
  | 'id.sifa.defs#domainPrimarySecondary'
  | 'id.sifa.defs#domainJournalism'
  | 'id.sifa.defs#domainFilmVideo'
  | 'id.sifa.defs#domainGaming'
  | 'id.sifa.defs#domainAdvertising'
  | 'id.sifa.defs#domainEcommerce'
  | 'id.sifa.defs#domainSupplyChain'
  | 'id.sifa.defs#domainAutomotive'
  | 'id.sifa.defs#domainAerospace'
  | 'id.sifa.defs#domainHardware'
  | 'id.sifa.defs#domainRenewables'
  | 'id.sifa.defs#domainOilGas'
  | 'id.sifa.defs#domainClimateTech'
  | 'id.sifa.defs#domainManagementConsulting'
  | 'id.sifa.defs#domainDevrel'
  | 'id.sifa.defs#domainHrRecruitment'
  | 'id.sifa.defs#domainIpLaw'
  | 'id.sifa.defs#domainCompliance'
  | 'id.sifa.defs#domainHumanRights'
  | 'id.sifa.defs#domainOpenSource'
  | 'id.sifa.defs#domainPublicPolicy'
  | 'id.sifa.defs#domainDefense'
  | 'id.sifa.defs#domainProptech'
  | 'id.sifa.defs#domainAutonomousVehicles'
  | 'id.sifa.defs#domainLogistics'
  | 'id.sifa.defs#domainAgritech'
  | 'id.sifa.defs#domainFoodTech'
  | 'id.sifa.defs#domainHotels'
  | 'id.sifa.defs#domainTravelTourism'
  | 'id.sifa.defs#domainFoodBeverage'
  | 'id.sifa.defs#domainNetworkInfra'
  | 'id.sifa.defs#domainMobileServices'
  | 'id.sifa.defs#domainExtraction'
  | 'id.sifa.defs#domainGeological'
  | 'id.sifa.defs#domainFashionDesign'
  | 'id.sifa.defs#domainTextileManufacturing'
  | 'id.sifa.defs#domainShipping'
  | 'id.sifa.defs#domainPortOperations'
  | 'id.sifa.defs#domainNavalArchitecture'
  | l.UnknownString

export type { DomainType }

/** Professional domain within an industry. Optional refinement of industryType. */
const domainType = l.string<{
  knownValues: [
    'id.sifa.defs#domainSoftwareEngineering',
    'id.sifa.defs#domainDataScience',
    'id.sifa.defs#domainCybersecurity',
    'id.sifa.defs#domainDevops',
    'id.sifa.defs#domainProductDesign',
    'id.sifa.defs#domainGameDev',
    'id.sifa.defs#domainBanking',
    'id.sifa.defs#domainFintech',
    'id.sifa.defs#domainInsurance',
    'id.sifa.defs#domainInvestmentMgmt',
    'id.sifa.defs#domainClinicalResearch',
    'id.sifa.defs#domainHealthtech',
    'id.sifa.defs#domainPharma',
    'id.sifa.defs#domainHigherEd',
    'id.sifa.defs#domainEdtech',
    'id.sifa.defs#domainPrimarySecondary',
    'id.sifa.defs#domainJournalism',
    'id.sifa.defs#domainFilmVideo',
    'id.sifa.defs#domainGaming',
    'id.sifa.defs#domainAdvertising',
    'id.sifa.defs#domainEcommerce',
    'id.sifa.defs#domainSupplyChain',
    'id.sifa.defs#domainAutomotive',
    'id.sifa.defs#domainAerospace',
    'id.sifa.defs#domainHardware',
    'id.sifa.defs#domainRenewables',
    'id.sifa.defs#domainOilGas',
    'id.sifa.defs#domainClimateTech',
    'id.sifa.defs#domainManagementConsulting',
    'id.sifa.defs#domainDevrel',
    'id.sifa.defs#domainHrRecruitment',
    'id.sifa.defs#domainIpLaw',
    'id.sifa.defs#domainCompliance',
    'id.sifa.defs#domainHumanRights',
    'id.sifa.defs#domainOpenSource',
    'id.sifa.defs#domainPublicPolicy',
    'id.sifa.defs#domainDefense',
    'id.sifa.defs#domainProptech',
    'id.sifa.defs#domainAutonomousVehicles',
    'id.sifa.defs#domainLogistics',
    'id.sifa.defs#domainAgritech',
    'id.sifa.defs#domainFoodTech',
    'id.sifa.defs#domainHotels',
    'id.sifa.defs#domainTravelTourism',
    'id.sifa.defs#domainFoodBeverage',
    'id.sifa.defs#domainNetworkInfra',
    'id.sifa.defs#domainMobileServices',
    'id.sifa.defs#domainExtraction',
    'id.sifa.defs#domainGeological',
    'id.sifa.defs#domainFashionDesign',
    'id.sifa.defs#domainTextileManufacturing',
    'id.sifa.defs#domainShipping',
    'id.sifa.defs#domainPortOperations',
    'id.sifa.defs#domainNavalArchitecture',
  ]
}>()

export { domainType }

/** Elementary proficiency. */
type Elementary = 'id.sifa.defs#elementary'

export type { Elementary }

/** Elementary proficiency. */
const elementary = l.token($nsid, 'elementary')

export { elementary }

/** Funded research, academic, or mission-driven position, typically selective. */
type Fellowship = 'id.sifa.defs#fellowship'

export type { Fellowship }

/** Funded research, academic, or mission-driven position, typically selective. */
const fellowship = l.token($nsid, 'fellowship')

export { fellowship }

/** Structured early-career work experience, often tied to studies. */
type Internship = 'id.sifa.defs#internship'

export type { Internship }

/** Structured early-career work experience, often tied to studies. */
const internship = l.token($nsid, 'internship')

export { internship }

/** Slides or presentation deck. */
type LinkSlides = 'id.sifa.defs#linkSlides'

export type { LinkSlides }

/** Slides or presentation deck. */
const linkSlides = l.token($nsid, 'linkSlides')

export { linkSlides }

/** Open to commissioned creative work (illustration, design, voice work, music, etc.). */
type Commissions = 'id.sifa.defs#commissions'

export type { Commissions }

/** Open to commissioned creative work (illustration, design, voice work, music, etc.). */
const commissions = l.token($nsid, 'commissions')

export { commissions }

/** Intellectual Property. */
type DomainIpLaw = 'id.sifa.defs#domainIpLaw'

export type { DomainIpLaw }

/** Intellectual Property. */
const domainIpLaw = l.token($nsid, 'domainIpLaw')

export { domainIpLaw }

/** A long-form write-up, article, or transcript of the talk. */
type LinkWriteup = 'id.sifa.defs#linkWriteup'

export type { LinkWriteup }

/** A long-form write-up, article, or transcript of the talk. */
const linkWriteup = l.token($nsid, 'linkWriteup')

export { linkWriteup }

/** RSS or Atom feed (blog, newsletter, podcast). */
type PlatformRss = 'id.sifa.defs#platformRss'

export type { PlatformRss }

/** RSS or Atom feed (blog, newsletter, podcast). */
const platformRss = l.token($nsid, 'platformRss')

export { platformRss }

/** Language proficiency level. Maps to LinkedIn's five-level scale for lossless import. */
type Proficiency =
  | 'id.sifa.defs#elementary'
  | 'id.sifa.defs#limitedWorking'
  | 'id.sifa.defs#professionalWorking'
  | 'id.sifa.defs#fullProfessional'
  | 'id.sifa.defs#native'
  | l.UnknownString

export type { Proficiency }

/** Language proficiency level. Maps to LinkedIn's five-level scale for lossless import. */
const proficiency = l.string<{
  knownValues: [
    'id.sifa.defs#elementary',
    'id.sifa.defs#limitedWorking',
    'id.sifa.defs#professionalWorking',
    'id.sifa.defs#fullProfessional',
    'id.sifa.defs#native',
  ]
}>()

export { proficiency }

/** Core team member with elevated involvement. */
type ProjectCore = 'id.sifa.defs#projectCore'

export type { ProjectCore }

/** Core team member with elevated involvement. */
const projectCore = l.token($nsid, 'projectCore')

export { projectCore }

/** Role within a collaborative project. */
type ProjectRole =
  | 'id.sifa.defs#projectOwner'
  | 'id.sifa.defs#projectCore'
  | 'id.sifa.defs#projectContributor'
  | l.UnknownString

export type { ProjectRole }

/** Role within a collaborative project. */
const projectRole = l.string<{
  knownValues: [
    'id.sifa.defs#projectOwner',
    'id.sifa.defs#projectCore',
    'id.sifa.defs#projectContributor',
  ]
}>()

export { projectRole }

/** Remote work within the same country as the employer. */
type RemoteLocal = 'id.sifa.defs#remoteLocal'

export type { RemoteLocal }

/** Remote work within the same country as the employer. */
const remoteLocal = l.token($nsid, 'remoteLocal')

export { remoteLocal }

/** DevOps & Infrastructure. */
type DomainDevops = 'id.sifa.defs#domainDevops'

export type { DomainDevops }

/** DevOps & Infrastructure. */
const domainDevops = l.token($nsid, 'domainDevops')

export { domainDevops }

/** Developer Relations. */
type DomainDevrel = 'id.sifa.defs#domainDevrel'

export type { DomainDevrel }

/** Developer Relations. */
const domainDevrel = l.token($nsid, 'domainDevrel')

export { domainDevrel }

/** Education Technology. */
type DomainEdtech = 'id.sifa.defs#domainEdtech'

export type { DomainEdtech }

/** Education Technology. */
const domainEdtech = l.token($nsid, 'domainEdtech')

export { domainEdtech }

/** Gaming & Interactive Media. */
type DomainGaming = 'id.sifa.defs#domainGaming'

export type { DomainGaming }

/** Gaming & Interactive Media. */
const domainGaming = l.token($nsid, 'domainGaming')

export { domainGaming }

/** Hotels & Accommodation. */
type DomainHotels = 'id.sifa.defs#domainHotels'

export type { DomainHotels }

/** Hotels & Accommodation. */
const domainHotels = l.token($nsid, 'domainHotels')

export { domainHotels }

/** Oil & Gas. */
type DomainOilGas = 'id.sifa.defs#domainOilGas'

export type { DomainOilGas }

/** Oil & Gas. */
const domainOilGas = l.token($nsid, 'domainOilGas')

export { domainOilGas }

/** Pharmaceuticals. */
type DomainPharma = 'id.sifa.defs#domainPharma'

export type { DomainPharma }

/** Pharmaceuticals. */
const domainPharma = l.token($nsid, 'domainPharma')

export { domainPharma }

/** Professional industry sector. */
type IndustryType =
  | 'id.sifa.defs#industryTechnology'
  | 'id.sifa.defs#industryFinance'
  | 'id.sifa.defs#industryHealthcare'
  | 'id.sifa.defs#industryEducation'
  | 'id.sifa.defs#industryMedia'
  | 'id.sifa.defs#industryRetail'
  | 'id.sifa.defs#industryManufacturing'
  | 'id.sifa.defs#industryEnergy'
  | 'id.sifa.defs#industryGovernment'
  | 'id.sifa.defs#industryLegal'
  | 'id.sifa.defs#industryConsulting'
  | 'id.sifa.defs#industryNonprofit'
  | 'id.sifa.defs#industryRealEstate'
  | 'id.sifa.defs#industryTransport'
  | 'id.sifa.defs#industryAgriculture'
  | 'id.sifa.defs#industryHospitality'
  | 'id.sifa.defs#industryTelecom'
  | 'id.sifa.defs#industryMining'
  | 'id.sifa.defs#industryFashion'
  | 'id.sifa.defs#industryMaritime'
  | 'id.sifa.defs#industryOther'
  | l.UnknownString

export type { IndustryType }

/** Professional industry sector. */
const industryType = l.string<{
  knownValues: [
    'id.sifa.defs#industryTechnology',
    'id.sifa.defs#industryFinance',
    'id.sifa.defs#industryHealthcare',
    'id.sifa.defs#industryEducation',
    'id.sifa.defs#industryMedia',
    'id.sifa.defs#industryRetail',
    'id.sifa.defs#industryManufacturing',
    'id.sifa.defs#industryEnergy',
    'id.sifa.defs#industryGovernment',
    'id.sifa.defs#industryLegal',
    'id.sifa.defs#industryConsulting',
    'id.sifa.defs#industryNonprofit',
    'id.sifa.defs#industryRealEstate',
    'id.sifa.defs#industryTransport',
    'id.sifa.defs#industryAgriculture',
    'id.sifa.defs#industryHospitality',
    'id.sifa.defs#industryTelecom',
    'id.sifa.defs#industryMining',
    'id.sifa.defs#industryFashion',
    'id.sifa.defs#industryMaritime',
    'id.sifa.defs#industryOther',
  ]
}>()

export { industryType }

/** The role a location plays in a user's professional profile. */
type LocationType =
  | 'id.sifa.defs#locationPrimary'
  | 'id.sifa.defs#locationBusiness'
  | 'id.sifa.defs#locationTravel'
  | l.UnknownString

export type { LocationType }

/** The role a location plays in a user's professional profile. */
const locationType = l.string<{
  knownValues: [
    'id.sifa.defs#locationPrimary',
    'id.sifa.defs#locationBusiness',
    'id.sifa.defs#locationTravel',
  ]
}>()

export { locationType }

/** Project owner with full management permissions. Multiple owners are supported. */
type ProjectOwner = 'id.sifa.defs#projectOwner'

export type { ProjectOwner }

/** Project owner with full management permissions. Multiple owners are supported. */
const projectOwner = l.token($nsid, 'projectOwner')

export { projectOwner }

/** Remote work from anywhere worldwide. */
type RemoteGlobal = 'id.sifa.defs#remoteGlobal'

export type { RemoteGlobal }

/** Remote work from anywhere worldwide. */
const remoteGlobal = l.token($nsid, 'remoteGlobal')

export { remoteGlobal }

/** Remote work within the same timezone region or continent. */
type RemoteRegion = 'id.sifa.defs#remoteRegion'

export type { RemoteRegion }

/** Remote work within the same timezone region or continent. */
const remoteRegion = l.token($nsid, 'remoteRegion')

export { remoteRegion }

/** Operating your own business or practice. May have employees. */
type SelfEmployed = 'id.sifa.defs#selfEmployed'

export type { SelfEmployed }

/** Operating your own business or practice. May have employees. */
const selfEmployed = l.token($nsid, 'selfEmployed')

export { selfEmployed }

/** Open to being mentored. */
type BeingMentored = 'id.sifa.defs#beingMentored'

export type { BeingMentored }

/** Open to being mentored. */
const beingMentored = l.token($nsid, 'beingMentored')

export { beingMentored }

/** Open to B2B contract or project-based freelance work, consulting, contract development. */
type ContractRoles = 'id.sifa.defs#contractRoles'

export type { ContractRoles }

/** Open to B2B contract or project-based freelance work, consulting, contract development. */
const contractRoles = l.token($nsid, 'contractRoles')

export { contractRoles }

/** Banking. */
type DomainBanking = 'id.sifa.defs#domainBanking'

export type { DomainBanking }

/** Banking. */
const domainBanking = l.token($nsid, 'domainBanking')

export { domainBanking }

/** Defense & Intelligence. */
type DomainDefense = 'id.sifa.defs#domainDefense'

export type { DomainDefense }

/** Defense & Intelligence. */
const domainDefense = l.token($nsid, 'domainDefense')

export { domainDefense }

/** Fintech. */
type DomainFintech = 'id.sifa.defs#domainFintech'

export type { DomainFintech }

/** Fintech. */
const domainFintech = l.token($nsid, 'domainFintech')

export { domainFintech }

/** Game Development. */
type DomainGameDev = 'id.sifa.defs#domainGameDev'

export type { DomainGameDev }

/** Game Development. */
const domainGameDev = l.token($nsid, 'domainGameDev')

export { domainGameDev }

/** Open to full-time employment opportunities. */
type FullTimeRoles = 'id.sifa.defs#fullTimeRoles'

export type { FullTimeRoles }

/** Open to full-time employment opportunities. */
const fullTimeRoles = l.token($nsid, 'fullTimeRoles')

export { fullTimeRoles }

/** Legal. */
type IndustryLegal = 'id.sifa.defs#industryLegal'

export type { IndustryLegal }

/** Legal. */
const industryLegal = l.token($nsid, 'industryLegal')

export { industryLegal }

/** Media & Entertainment. */
type IndustryMedia = 'id.sifa.defs#industryMedia'

export type { IndustryMedia }

/** Media & Entertainment. */
const industryMedia = l.token($nsid, 'industryMedia')

export { industryMedia }

/** Other industry. */
type IndustryOther = 'id.sifa.defs#industryOther'

export type { IndustryOther }

/** Other industry. */
const industryOther = l.token($nsid, 'industryOther')

export { industryOther }

/** Interpersonal and communication skills. */
type Interpersonal = 'id.sifa.defs#interpersonal'

export type { Interpersonal }

/** Interpersonal and communication skills. */
const interpersonal = l.token($nsid, 'interpersonal')

export { interpersonal }

/** Video or audio recording of the presentation. */
type LinkRecording = 'id.sifa.defs#linkRecording'

export type { LinkRecording }

/** Video or audio recording of the presentation. */
const linkRecording = l.token($nsid, 'linkRecording')

export { linkRecording }

/** Open to part-time employment opportunities. */
type PartTimeRoles = 'id.sifa.defs#partTimeRoles'

export type { PartTimeRoles }

/** Open to part-time employment opportunities. */
const partTimeRoles = l.token($nsid, 'partTimeRoles')

export { partTimeRoles }

/** Gitea account on a self-hosted instance. */
type PlatformGitea = 'id.sifa.defs#platformGitea'

export type { PlatformGitea }

/** Gitea account on a self-hosted instance. */
const platformGitea = l.token($nsid, 'platformGitea')

export { platformGitea }

/** ORCID researcher identifier. */
type PlatformOrcid = 'id.sifa.defs#platformOrcid'

export type { PlatformOrcid }

/** ORCID researcher identifier. */
const platformOrcid = l.token($nsid, 'platformOrcid')

export { platformOrcid }

/** Other platform not covered by specific tokens. */
type PlatformOther = 'id.sifa.defs#platformOther'

export type { PlatformOther }

/** Other platform not covered by specific tokens. */
const platformOther = l.token($nsid, 'platformOther')

export { platformOther }

/** Project is actively maintained or in development. */
type ProjectActive = 'id.sifa.defs#projectActive'

export type { ProjectActive }

/** Project is actively maintained or in development. */
const projectActive = l.token($nsid, 'projectActive')

export { projectActive }

/** Current status of a collaborative project. */
type ProjectStatus =
  | 'id.sifa.defs#projectActive'
  | 'id.sifa.defs#projectCompleted'
  | 'id.sifa.defs#projectArchived'
  | l.UnknownString

export type { ProjectStatus }

/** Current status of a collaborative project. */
const projectStatus = l.string<{
  knownValues: [
    'id.sifa.defs#projectActive',
    'id.sifa.defs#projectCompleted',
    'id.sifa.defs#projectArchived',
  ]
}>()

export { projectStatus }

/** Broad category for grouping skills. */
type SkillCategory =
  | 'id.sifa.defs#technical'
  | 'id.sifa.defs#business'
  | 'id.sifa.defs#creative'
  | 'id.sifa.defs#interpersonal'
  | 'id.sifa.defs#language'
  | 'id.sifa.defs#industry'
  | l.UnknownString

export type { SkillCategory }

/** Broad category for grouping skills. */
const skillCategory = l.string<{
  knownValues: [
    'id.sifa.defs#technical',
    'id.sifa.defs#business',
    'id.sifa.defs#creative',
    'id.sifa.defs#interpersonal',
    'id.sifa.defs#language',
    'id.sifa.defs#industry',
  ]
}>()

export { skillCategory }

/** The workplace arrangement. */
type WorkplaceType =
  | 'id.sifa.defs#onSite'
  | 'id.sifa.defs#remote'
  | 'id.sifa.defs#hybrid'
  | 'id.sifa.defs#remoteLocal'
  | 'id.sifa.defs#remoteRegion'
  | 'id.sifa.defs#remoteGlobal'
  | l.UnknownString

export type { WorkplaceType }

/** The workplace arrangement. */
const workplaceType = l.string<{
  knownValues: [
    'id.sifa.defs#onSite',
    'id.sifa.defs#remote',
    'id.sifa.defs#hybrid',
    'id.sifa.defs#remoteLocal',
    'id.sifa.defs#remoteRegion',
    'id.sifa.defs#remoteGlobal',
  ]
}>()

export { workplaceType }

/** Formal training-to-certification program combining paid work and education. */
type Apprenticeship = 'id.sifa.defs#apprenticeship'

export type { Apprenticeship }

/** Formal training-to-certification program combining paid work and education. */
const apprenticeship = l.token($nsid, 'apprenticeship')

export { apprenticeship }

/** Open to advisory or board positions. */
type BoardPositions = 'id.sifa.defs#boardPositions'

export type { BoardPositions }

/** Open to advisory or board positions. */
const boardPositions = l.token($nsid, 'boardPositions')

export { boardPositions }

/** Open to project collaborations. */
type Collaborations = 'id.sifa.defs#collaborations'

export type { Collaborations }

/** Open to project collaborations. */
const collaborations = l.token($nsid, 'collaborations')

export { collaborations }

/** Agricultural Technology. */
type DomainAgritech = 'id.sifa.defs#domainAgritech'

export type { DomainAgritech }

/** Agricultural Technology. */
const domainAgritech = l.token($nsid, 'domainAgritech')

export { domainAgritech }

/** Food Technology & Processing. */
type DomainFoodTech = 'id.sifa.defs#domainFoodTech'

export type { DomainFoodTech }

/** Food Technology & Processing. */
const domainFoodTech = l.token($nsid, 'domainFoodTech')

export { domainFoodTech }

/** Hardware & Electronics. */
type DomainHardware = 'id.sifa.defs#domainHardware'

export type { DomainHardware }

/** Hardware & Electronics. */
const domainHardware = l.token($nsid, 'domainHardware')

export { domainHardware }

/** Higher Education. */
type DomainHigherEd = 'id.sifa.defs#domainHigherEd'

export type { DomainHigherEd }

/** Higher Education. */
const domainHigherEd = l.token($nsid, 'domainHigherEd')

export { domainHigherEd }

/** Property Technology. */
type DomainProptech = 'id.sifa.defs#domainProptech'

export type { DomainProptech }

/** Property Technology. */
const domainProptech = l.token($nsid, 'domainProptech')

export { domainProptech }

/** Shipping & Freight. */
type DomainShipping = 'id.sifa.defs#domainShipping'

export type { DomainShipping }

/** Shipping & Freight. */
const domainShipping = l.token($nsid, 'domainShipping')

export { domainShipping }

/** The type of employment arrangement. */
type EmploymentType =
  | 'id.sifa.defs#fullTime'
  | 'id.sifa.defs#partTime'
  | 'id.sifa.defs#temporary'
  | 'id.sifa.defs#seasonal'
  | 'id.sifa.defs#contract'
  | 'id.sifa.defs#freelance'
  | 'id.sifa.defs#selfEmployed'
  | 'id.sifa.defs#independentWork'
  | 'id.sifa.defs#internship'
  | 'id.sifa.defs#apprenticeship'
  | 'id.sifa.defs#fellowship'
  | 'id.sifa.defs#trainee'
  | 'id.sifa.defs#volunteer'
  | l.UnknownString

export type { EmploymentType }

/** The type of employment arrangement. */
const employmentType = l.string<{
  knownValues: [
    'id.sifa.defs#fullTime',
    'id.sifa.defs#partTime',
    'id.sifa.defs#temporary',
    'id.sifa.defs#seasonal',
    'id.sifa.defs#contract',
    'id.sifa.defs#freelance',
    'id.sifa.defs#selfEmployed',
    'id.sifa.defs#independentWork',
    'id.sifa.defs#internship',
    'id.sifa.defs#apprenticeship',
    'id.sifa.defs#fellowship',
    'id.sifa.defs#trainee',
    'id.sifa.defs#volunteer',
  ]
}>()

export { employmentType }

/** An industry/domain pair. Industry is required; domain is an optional refinement within the industry. */
type IndustryDomain = {
  $type?: 'id.sifa.defs#industryDomain'

  /**
   * Professional domain within the selected industry. Optional refinement.
   */
  domain?:
    | 'id.sifa.defs#domainSoftwareEngineering'
    | 'id.sifa.defs#domainDataScience'
    | 'id.sifa.defs#domainCybersecurity'
    | 'id.sifa.defs#domainDevops'
    | 'id.sifa.defs#domainProductDesign'
    | 'id.sifa.defs#domainGameDev'
    | 'id.sifa.defs#domainBanking'
    | 'id.sifa.defs#domainFintech'
    | 'id.sifa.defs#domainInsurance'
    | 'id.sifa.defs#domainInvestmentMgmt'
    | 'id.sifa.defs#domainClinicalResearch'
    | 'id.sifa.defs#domainHealthtech'
    | 'id.sifa.defs#domainPharma'
    | 'id.sifa.defs#domainHigherEd'
    | 'id.sifa.defs#domainEdtech'
    | 'id.sifa.defs#domainPrimarySecondary'
    | 'id.sifa.defs#domainJournalism'
    | 'id.sifa.defs#domainFilmVideo'
    | 'id.sifa.defs#domainGaming'
    | 'id.sifa.defs#domainAdvertising'
    | 'id.sifa.defs#domainEcommerce'
    | 'id.sifa.defs#domainSupplyChain'
    | 'id.sifa.defs#domainAutomotive'
    | 'id.sifa.defs#domainAerospace'
    | 'id.sifa.defs#domainHardware'
    | 'id.sifa.defs#domainRenewables'
    | 'id.sifa.defs#domainOilGas'
    | 'id.sifa.defs#domainClimateTech'
    | 'id.sifa.defs#domainManagementConsulting'
    | 'id.sifa.defs#domainDevrel'
    | 'id.sifa.defs#domainHrRecruitment'
    | 'id.sifa.defs#domainIpLaw'
    | 'id.sifa.defs#domainCompliance'
    | 'id.sifa.defs#domainHumanRights'
    | 'id.sifa.defs#domainOpenSource'
    | 'id.sifa.defs#domainPublicPolicy'
    | 'id.sifa.defs#domainDefense'
    | 'id.sifa.defs#domainProptech'
    | 'id.sifa.defs#domainAutonomousVehicles'
    | 'id.sifa.defs#domainLogistics'
    | 'id.sifa.defs#domainAgritech'
    | 'id.sifa.defs#domainFoodTech'
    | 'id.sifa.defs#domainHotels'
    | 'id.sifa.defs#domainTravelTourism'
    | 'id.sifa.defs#domainFoodBeverage'
    | 'id.sifa.defs#domainNetworkInfra'
    | 'id.sifa.defs#domainMobileServices'
    | 'id.sifa.defs#domainExtraction'
    | 'id.sifa.defs#domainGeological'
    | 'id.sifa.defs#domainFashionDesign'
    | 'id.sifa.defs#domainTextileManufacturing'
    | 'id.sifa.defs#domainShipping'
    | 'id.sifa.defs#domainPortOperations'
    | 'id.sifa.defs#domainNavalArchitecture'
    | l.UnknownString

  /**
   * Professional industry sector token.
   */
  industry:
    | 'id.sifa.defs#industryTechnology'
    | 'id.sifa.defs#industryFinance'
    | 'id.sifa.defs#industryHealthcare'
    | 'id.sifa.defs#industryEducation'
    | 'id.sifa.defs#industryMedia'
    | 'id.sifa.defs#industryRetail'
    | 'id.sifa.defs#industryManufacturing'
    | 'id.sifa.defs#industryEnergy'
    | 'id.sifa.defs#industryGovernment'
    | 'id.sifa.defs#industryLegal'
    | 'id.sifa.defs#industryConsulting'
    | 'id.sifa.defs#industryNonprofit'
    | 'id.sifa.defs#industryRealEstate'
    | 'id.sifa.defs#industryTransport'
    | 'id.sifa.defs#industryAgriculture'
    | 'id.sifa.defs#industryHospitality'
    | 'id.sifa.defs#industryTelecom'
    | 'id.sifa.defs#industryMining'
    | 'id.sifa.defs#industryFashion'
    | 'id.sifa.defs#industryMaritime'
    | 'id.sifa.defs#industryOther'
    | l.UnknownString
}

export type { IndustryDomain }

/** An industry/domain pair. Industry is required; domain is an optional refinement within the industry. */
const industryDomain = l.typedObject<IndustryDomain>(
  $nsid,
  'industryDomain',
  l.object({
    domain: l.optional(
      l.string<{
        knownValues: [
          'id.sifa.defs#domainSoftwareEngineering',
          'id.sifa.defs#domainDataScience',
          'id.sifa.defs#domainCybersecurity',
          'id.sifa.defs#domainDevops',
          'id.sifa.defs#domainProductDesign',
          'id.sifa.defs#domainGameDev',
          'id.sifa.defs#domainBanking',
          'id.sifa.defs#domainFintech',
          'id.sifa.defs#domainInsurance',
          'id.sifa.defs#domainInvestmentMgmt',
          'id.sifa.defs#domainClinicalResearch',
          'id.sifa.defs#domainHealthtech',
          'id.sifa.defs#domainPharma',
          'id.sifa.defs#domainHigherEd',
          'id.sifa.defs#domainEdtech',
          'id.sifa.defs#domainPrimarySecondary',
          'id.sifa.defs#domainJournalism',
          'id.sifa.defs#domainFilmVideo',
          'id.sifa.defs#domainGaming',
          'id.sifa.defs#domainAdvertising',
          'id.sifa.defs#domainEcommerce',
          'id.sifa.defs#domainSupplyChain',
          'id.sifa.defs#domainAutomotive',
          'id.sifa.defs#domainAerospace',
          'id.sifa.defs#domainHardware',
          'id.sifa.defs#domainRenewables',
          'id.sifa.defs#domainOilGas',
          'id.sifa.defs#domainClimateTech',
          'id.sifa.defs#domainManagementConsulting',
          'id.sifa.defs#domainDevrel',
          'id.sifa.defs#domainHrRecruitment',
          'id.sifa.defs#domainIpLaw',
          'id.sifa.defs#domainCompliance',
          'id.sifa.defs#domainHumanRights',
          'id.sifa.defs#domainOpenSource',
          'id.sifa.defs#domainPublicPolicy',
          'id.sifa.defs#domainDefense',
          'id.sifa.defs#domainProptech',
          'id.sifa.defs#domainAutonomousVehicles',
          'id.sifa.defs#domainLogistics',
          'id.sifa.defs#domainAgritech',
          'id.sifa.defs#domainFoodTech',
          'id.sifa.defs#domainHotels',
          'id.sifa.defs#domainTravelTourism',
          'id.sifa.defs#domainFoodBeverage',
          'id.sifa.defs#domainNetworkInfra',
          'id.sifa.defs#domainMobileServices',
          'id.sifa.defs#domainExtraction',
          'id.sifa.defs#domainGeological',
          'id.sifa.defs#domainFashionDesign',
          'id.sifa.defs#domainTextileManufacturing',
          'id.sifa.defs#domainShipping',
          'id.sifa.defs#domainPortOperations',
          'id.sifa.defs#domainNavalArchitecture',
        ]
      }>(),
    ),
    industry: l.string<{
      knownValues: [
        'id.sifa.defs#industryTechnology',
        'id.sifa.defs#industryFinance',
        'id.sifa.defs#industryHealthcare',
        'id.sifa.defs#industryEducation',
        'id.sifa.defs#industryMedia',
        'id.sifa.defs#industryRetail',
        'id.sifa.defs#industryManufacturing',
        'id.sifa.defs#industryEnergy',
        'id.sifa.defs#industryGovernment',
        'id.sifa.defs#industryLegal',
        'id.sifa.defs#industryConsulting',
        'id.sifa.defs#industryNonprofit',
        'id.sifa.defs#industryRealEstate',
        'id.sifa.defs#industryTransport',
        'id.sifa.defs#industryAgriculture',
        'id.sifa.defs#industryHospitality',
        'id.sifa.defs#industryTelecom',
        'id.sifa.defs#industryMining',
        'id.sifa.defs#industryFashion',
        'id.sifa.defs#industryMaritime',
        'id.sifa.defs#industryOther',
      ]
    }>(),
  }),
)

export { industryDomain }

/** Energy & Environment. */
type IndustryEnergy = 'id.sifa.defs#industryEnergy'

export type { IndustryEnergy }

/** Energy & Environment. */
const industryEnergy = l.token($nsid, 'industryEnergy')

export { industryEnergy }

/** Mining & Resources. */
type IndustryMining = 'id.sifa.defs#industryMining'

export type { IndustryMining }

/** Mining & Resources. */
const industryMining = l.token($nsid, 'industryMining')

export { industryMining }

/** Retail & E-commerce. */
type IndustryRetail = 'id.sifa.defs#industryRetail'

export type { IndustryRetail }

/** Retail & E-commerce. */
const industryRetail = l.token($nsid, 'industryRetail')

export { industryRetail }

/** Limited working proficiency. */
type LimitedWorking = 'id.sifa.defs#limitedWorking'

export type { LimitedWorking }

/** Limited working proficiency. */
const limitedWorking = l.token($nsid, 'limitedWorking')

export { limitedWorking }

/** Frequent travel or temporary location. */
type LocationTravel = 'id.sifa.defs#locationTravel'

export type { LocationTravel }

/** Frequent travel or temporary location. */
const locationTravel = l.token($nsid, 'locationTravel')

export { locationTravel }

/** GitHub account. */
type PlatformGithub = 'id.sifa.defs#platformGithub'

export type { PlatformGithub }

/** GitHub account. */
const platformGithub = l.token($nsid, 'platformGithub')

export { platformGithub }

/** GitLab account (gitlab.com or self-hosted). */
type PlatformGitlab = 'id.sifa.defs#platformGitlab'

export type { PlatformGitlab }

/** GitLab account (gitlab.com or self-hosted). */
const platformGitlab = l.token($nsid, 'platformGitlab')

export { platformGitlab }

/** Aerospace & Defense. */
type DomainAerospace = 'id.sifa.defs#domainAerospace'

export type { DomainAerospace }

/** Aerospace & Defense. */
const domainAerospace = l.token($nsid, 'domainAerospace')

export { domainAerospace }

/** E-commerce. */
type DomainEcommerce = 'id.sifa.defs#domainEcommerce'

export type { DomainEcommerce }

/** E-commerce. */
const domainEcommerce = l.token($nsid, 'domainEcommerce')

export { domainEcommerce }

/** Film & Video. */
type DomainFilmVideo = 'id.sifa.defs#domainFilmVideo'

export type { DomainFilmVideo }

/** Film & Video. */
const domainFilmVideo = l.token($nsid, 'domainFilmVideo')

export { domainFilmVideo }

/** Insurance. */
type DomainInsurance = 'id.sifa.defs#domainInsurance'

export type { DomainInsurance }

/** Insurance. */
const domainInsurance = l.token($nsid, 'domainInsurance')

export { domainInsurance }

/** Logistics & Warehousing. */
type DomainLogistics = 'id.sifa.defs#domainLogistics'

export type { DomainLogistics }

/** Logistics & Warehousing. */
const domainLogistics = l.token($nsid, 'domainLogistics')

export { domainLogistics }

/** Self-initiated, sustained work I lead — community building, content creation, ecosystem contribution, or similar. May involve a registered entity but does not pay me personally. Often run alongside other employment. */
type IndependentWork = 'id.sifa.defs#independentWork'

export type { IndependentWork }

/** Self-initiated, sustained work I lead — community building, content creation, ecosystem contribution, or similar. May involve a registered entity but does not pay me personally. Often run alongside other employment. */
const independentWork = l.token($nsid, 'independentWork')

export { independentWork }

/** Fashion & Textiles. */
type IndustryFashion = 'id.sifa.defs#industryFashion'

export type { IndustryFashion }

/** Fashion & Textiles. */
const industryFashion = l.token($nsid, 'industryFashion')

export { industryFashion }

/** Finance & Banking. */
type IndustryFinance = 'id.sifa.defs#industryFinance'

export type { IndustryFinance }

/** Finance & Banking. */
const industryFinance = l.token($nsid, 'industryFinance')

export { industryFinance }

/** Telecommunications. */
type IndustryTelecom = 'id.sifa.defs#industryTelecom'

export type { IndustryTelecom }

/** Telecommunications. */
const industryTelecom = l.token($nsid, 'industryTelecom')

export { industryTelecom }

/** Primary residence or home location. */
type LocationPrimary = 'id.sifa.defs#locationPrimary'

export type { LocationPrimary }

/** Primary residence or home location. */
const locationPrimary = l.token($nsid, 'locationPrimary')

export { locationPrimary }

/** Open to mentoring others. */
type MentoringOthers = 'id.sifa.defs#mentoringOthers'

export type { MentoringOthers }

/** Open to mentoring others. */
const mentoringOthers = l.token($nsid, 'mentoringOthers')

export { mentoringOthers }

/** Forgejo account on a self-hosted instance other than Codeberg. */
type PlatformForgejo = 'id.sifa.defs#platformForgejo'

export type { PlatformForgejo }

/** Forgejo account on a self-hosted instance other than Codeberg. */
const platformForgejo = l.token($nsid, 'platformForgejo')

export { platformForgejo }

/** Twitter/X account. */
type PlatformTwitter = 'id.sifa.defs#platformTwitter'

export type { PlatformTwitter }

/** Twitter/X account. */
const platformTwitter = l.token($nsid, 'platformTwitter')

export { platformTwitter }

/** Personal or professional website. */
type PlatformWebsite = 'id.sifa.defs#platformWebsite'

export type { PlatformWebsite }

/** Personal or professional website. */
const platformWebsite = l.token($nsid, 'platformWebsite')

export { platformWebsite }

/** YouTube channel. */
type PlatformYoutube = 'id.sifa.defs#platformYoutube'

export type { PlatformYoutube }

/** YouTube channel. */
const platformYoutube = l.token($nsid, 'platformYoutube')

export { platformYoutube }

/** Project is archived and no longer active. */
type ProjectArchived = 'id.sifa.defs#projectArchived'

export type { ProjectArchived }

/** Project is archived and no longer active. */
const projectArchived = l.token($nsid, 'projectArchived')

export { projectArchived }

/** Automotive. */
type DomainAutomotive = 'id.sifa.defs#domainAutomotive'

export type { DomainAutomotive }

/** Automotive. */
const domainAutomotive = l.token($nsid, 'domainAutomotive')

export { domainAutomotive }

/** Compliance & Regulatory. */
type DomainCompliance = 'id.sifa.defs#domainCompliance'

export type { DomainCompliance }

/** Compliance & Regulatory. */
const domainCompliance = l.token($nsid, 'domainCompliance')

export { domainCompliance }

/** Extraction & Processing. */
type DomainExtraction = 'id.sifa.defs#domainExtraction'

export type { DomainExtraction }

/** Extraction & Processing. */
const domainExtraction = l.token($nsid, 'domainExtraction')

export { domainExtraction }

/** Geological Services. */
type DomainGeological = 'id.sifa.defs#domainGeological'

export type { DomainGeological }

/** Geological Services. */
const domainGeological = l.token($nsid, 'domainGeological')

export { domainGeological }

/** Health Technology. */
type DomainHealthtech = 'id.sifa.defs#domainHealthtech'

export type { DomainHealthtech }

/** Health Technology. */
const domainHealthtech = l.token($nsid, 'domainHealthtech')

export { domainHealthtech }

/** Journalism. */
type DomainJournalism = 'id.sifa.defs#domainJournalism'

export type { DomainJournalism }

/** Journalism. */
const domainJournalism = l.token($nsid, 'domainJournalism')

export { domainJournalism }

/** Open Source. */
type DomainOpenSource = 'id.sifa.defs#domainOpenSource'

export type { DomainOpenSource }

/** Open Source. */
const domainOpenSource = l.token($nsid, 'domainOpenSource')

export { domainOpenSource }

/** Renewable Energy. */
type DomainRenewables = 'id.sifa.defs#domainRenewables'

export type { DomainRenewables }

/** Renewable Energy. */
const domainRenewables = l.token($nsid, 'domainRenewables')

export { domainRenewables }

/** Platform type for an external account linked to a Sifa profile. */
type ExternalPlatform =
  | 'id.sifa.defs#platformRss'
  | 'id.sifa.defs#platformFediverse'
  | 'id.sifa.defs#platformTwitter'
  | 'id.sifa.defs#platformInstagram'
  | 'id.sifa.defs#platformGithub'
  | 'id.sifa.defs#platformCodeberg'
  | 'id.sifa.defs#platformGitlab'
  | 'id.sifa.defs#platformForgejo'
  | 'id.sifa.defs#platformGitea'
  | 'id.sifa.defs#platformYoutube'
  | 'id.sifa.defs#platformLinkedin'
  | 'id.sifa.defs#platformSubstack'
  | 'id.sifa.defs#platformWebsite'
  | 'id.sifa.defs#platformOrcid'
  | 'id.sifa.defs#platformOther'
  | l.UnknownString

export type { ExternalPlatform }

/** Platform type for an external account linked to a Sifa profile. */
const externalPlatform = l.string<{
  knownValues: [
    'id.sifa.defs#platformRss',
    'id.sifa.defs#platformFediverse',
    'id.sifa.defs#platformTwitter',
    'id.sifa.defs#platformInstagram',
    'id.sifa.defs#platformGithub',
    'id.sifa.defs#platformCodeberg',
    'id.sifa.defs#platformGitlab',
    'id.sifa.defs#platformForgejo',
    'id.sifa.defs#platformGitea',
    'id.sifa.defs#platformYoutube',
    'id.sifa.defs#platformLinkedin',
    'id.sifa.defs#platformSubstack',
    'id.sifa.defs#platformWebsite',
    'id.sifa.defs#platformOrcid',
    'id.sifa.defs#platformOther',
  ]
}>()

export { externalPlatform }

/** Full professional proficiency. */
type FullProfessional = 'id.sifa.defs#fullProfessional'

export type { FullProfessional }

/** Full professional proficiency. */
const fullProfessional = l.token($nsid, 'fullProfessional')

export { fullProfessional }

/** Maritime & Shipping. */
type IndustryMaritime = 'id.sifa.defs#industryMaritime'

export type { IndustryMaritime }

/** Maritime & Shipping. */
const industryMaritime = l.token($nsid, 'industryMaritime')

export { industryMaritime }

/** Registration or ticket page. */
type LinkRegistration = 'id.sifa.defs#linkRegistration'

export type { LinkRegistration }

/** Registration or ticket page. */
const linkRegistration = l.token($nsid, 'linkRegistration')

export { linkRegistration }

/** Business or operational location. */
type LocationBusiness = 'id.sifa.defs#locationBusiness'

export type { LocationBusiness }

/** Business or operational location. */
const locationBusiness = l.token($nsid, 'locationBusiness')

export { locationBusiness }

/** The type of opportunity the user is open to. */
type OpenToWorkStatus =
  | 'id.sifa.defs#fullTimeRoles'
  | 'id.sifa.defs#partTimeRoles'
  | 'id.sifa.defs#contractRoles'
  | 'id.sifa.defs#commissions'
  | 'id.sifa.defs#boardPositions'
  | 'id.sifa.defs#mentoringOthers'
  | 'id.sifa.defs#beingMentored'
  | 'id.sifa.defs#collaborations'
  | l.UnknownString

export type { OpenToWorkStatus }

/** The type of opportunity the user is open to. */
const openToWorkStatus = l.string<{
  knownValues: [
    'id.sifa.defs#fullTimeRoles',
    'id.sifa.defs#partTimeRoles',
    'id.sifa.defs#contractRoles',
    'id.sifa.defs#commissions',
    'id.sifa.defs#boardPositions',
    'id.sifa.defs#mentoringOthers',
    'id.sifa.defs#beingMentored',
    'id.sifa.defs#collaborations',
  ]
}>()

export { openToWorkStatus }

/** Codeberg account. */
type PlatformCodeberg = 'id.sifa.defs#platformCodeberg'

export type { PlatformCodeberg }

/** Codeberg account. */
const platformCodeberg = l.token($nsid, 'platformCodeberg')

export { platformCodeberg }

/** LinkedIn profile. */
type PlatformLinkedin = 'id.sifa.defs#platformLinkedin'

export type { PlatformLinkedin }

/** LinkedIn profile. */
const platformLinkedin = l.token($nsid, 'platformLinkedin')

export { platformLinkedin }

/** Substack newsletter. */
type PlatformSubstack = 'id.sifa.defs#platformSubstack'

export type { PlatformSubstack }

/** Substack newsletter. */
const platformSubstack = l.token($nsid, 'platformSubstack')

export { platformSubstack }

/** A related link for a presentation or one of its deliveries. */
type PresentationLink = {
  $type?: 'id.sifa.defs#presentationLink'

  /**
   * The link URL.
   */
  uri: l.UriString

  /**
   * Optional link category, used to pick an icon. Open set; see id.sifa.defs#presentationLinkType.
   */
  type?:
    | 'id.sifa.defs#linkSlides'
    | 'id.sifa.defs#linkRecording'
    | 'id.sifa.defs#linkEvent'
    | 'id.sifa.defs#linkRegistration'
    | 'id.sifa.defs#linkWriteup'
    | 'id.sifa.defs#linkOther'
    | l.UnknownString

  /**
   * Optional display label (e.g., 'Watch recording', 'Slides').
   */
  label?: string
}

export type { PresentationLink }

/** A related link for a presentation or one of its deliveries. */
const presentationLink = l.typedObject<PresentationLink>(
  $nsid,
  'presentationLink',
  l.object({
    uri: l.string({ format: 'uri' }),
    type: l.optional(
      l.string<{
        knownValues: [
          'id.sifa.defs#linkSlides',
          'id.sifa.defs#linkRecording',
          'id.sifa.defs#linkEvent',
          'id.sifa.defs#linkRegistration',
          'id.sifa.defs#linkWriteup',
          'id.sifa.defs#linkOther',
        ]
      }>(),
    ),
    label: l.optional(l.string({ maxLength: 640, maxGraphemes: 64 })),
  }),
)

export { presentationLink }

/** The user's role in a presentation or session. Open set. */
type PresentationRole =
  | 'id.sifa.defs#presenter'
  | 'id.sifa.defs#panelist'
  | 'id.sifa.defs#keynote'
  | 'id.sifa.defs#workshop'
  | 'id.sifa.defs#host'
  | l.UnknownString

export type { PresentationRole }

/** The user's role in a presentation or session. Open set. */
const presentationRole = l.string<{
  knownValues: [
    'id.sifa.defs#presenter',
    'id.sifa.defs#panelist',
    'id.sifa.defs#keynote',
    'id.sifa.defs#workshop',
    'id.sifa.defs#host',
  ]
}>()

export { presentationRole }

/** Project has been completed. */
type ProjectCompleted = 'id.sifa.defs#projectCompleted'

export type { ProjectCompleted }

/** Project has been completed. */
const projectCompleted = l.token($nsid, 'projectCompleted')

export { projectCompleted }

/** Advertising & Marketing. */
type DomainAdvertising = 'id.sifa.defs#domainAdvertising'

export type { DomainAdvertising }

/** Advertising & Marketing. */
const domainAdvertising = l.token($nsid, 'domainAdvertising')

export { domainAdvertising }

/** Climate Tech. */
type DomainClimateTech = 'id.sifa.defs#domainClimateTech'

export type { DomainClimateTech }

/** Climate Tech. */
const domainClimateTech = l.token($nsid, 'domainClimateTech')

export { domainClimateTech }

/** Data Science & ML. */
type DomainDataScience = 'id.sifa.defs#domainDataScience'

export type { DomainDataScience }

/** Data Science & ML. */
const domainDataScience = l.token($nsid, 'domainDataScience')

export { domainDataScience }

/** Human Rights. */
type DomainHumanRights = 'id.sifa.defs#domainHumanRights'

export type { DomainHumanRights }

/** Human Rights. */
const domainHumanRights = l.token($nsid, 'domainHumanRights')

export { domainHumanRights }

/** Supply Chain & Fulfillment. */
type DomainSupplyChain = 'id.sifa.defs#domainSupplyChain'

export type { DomainSupplyChain }

/** Supply Chain & Fulfillment. */
const domainSupplyChain = l.token($nsid, 'domainSupplyChain')

export { domainSupplyChain }

/** A reference to a record in another repository or lexicon by AT-URI. The CID is optional: it pins a specific version as an integrity hint, but consumers should resolve the AT-URI live so the reference tracks edits to the target. */
type ExternalRecordRef = {
  $type?: 'id.sifa.defs#externalRecordRef'

  /**
   * Optional CID of a specific version of the referenced record. Used as an integrity hint only; live resolution is by AT-URI.
   */
  cid?: l.CidString

  /**
   * AT-URI of the referenced record.
   */
  uri: l.AtUriString
}

export type { ExternalRecordRef }

/** A reference to a record in another repository or lexicon by AT-URI. The CID is optional: it pins a specific version as an integrity hint, but consumers should resolve the AT-URI live so the reference tracks edits to the target. */
const externalRecordRef = l.typedObject<ExternalRecordRef>(
  $nsid,
  'externalRecordRef',
  l.object({
    cid: l.optional(l.string({ format: 'cid' })),
    uri: l.string({ format: 'at-uri' }),
  }),
)

export { externalRecordRef }

/** Education & Research. */
type IndustryEducation = 'id.sifa.defs#industryEducation'

export type { IndustryEducation }

/** Education & Research. */
const industryEducation = l.token($nsid, 'industryEducation')

export { industryEducation }

/** Non-profit & Social Impact. */
type IndustryNonprofit = 'id.sifa.defs#industryNonprofit'

export type { IndustryNonprofit }

/** Non-profit & Social Impact. */
const industryNonprofit = l.token($nsid, 'industryNonprofit')

export { industryNonprofit }

/** Transportation & Logistics. */
type IndustryTransport = 'id.sifa.defs#industryTransport'

export type { IndustryTransport }

/** Transportation & Logistics. */
const industryTransport = l.token($nsid, 'industryTransport')

export { industryTransport }

/** Fediverse account (Mastodon, Misskey, Pleroma, etc.). */
type PlatformFediverse = 'id.sifa.defs#platformFediverse'

export type { PlatformFediverse }

/** Fediverse account (Mastodon, Misskey, Pleroma, etc.). */
const platformFediverse = l.token($nsid, 'platformFediverse')

export { platformFediverse }

/** Instagram account. */
type PlatformInstagram = 'id.sifa.defs#platformInstagram'

export type { PlatformInstagram }

/** Instagram account. */
const platformInstagram = l.token($nsid, 'platformInstagram')

export { platformInstagram }

/** Food & Beverage. */
type DomainFoodBeverage = 'id.sifa.defs#domainFoodBeverage'

export type { DomainFoodBeverage }

/** Food & Beverage. */
const domainFoodBeverage = l.token($nsid, 'domainFoodBeverage')

export { domainFoodBeverage }

/** Network Infrastructure. */
type DomainNetworkInfra = 'id.sifa.defs#domainNetworkInfra'

export type { DomainNetworkInfra }

/** Network Infrastructure. */
const domainNetworkInfra = l.token($nsid, 'domainNetworkInfra')

export { domainNetworkInfra }

/** Public Policy. */
type DomainPublicPolicy = 'id.sifa.defs#domainPublicPolicy'

export type { DomainPublicPolicy }

/** Public Policy. */
const domainPublicPolicy = l.token($nsid, 'domainPublicPolicy')

export { domainPublicPolicy }

/** Consulting & Professional Services. */
type IndustryConsulting = 'id.sifa.defs#industryConsulting'

export type { IndustryConsulting }

/** Consulting & Professional Services. */
const industryConsulting = l.token($nsid, 'industryConsulting')

export { industryConsulting }

/** Government & Public Sector. */
type IndustryGovernment = 'id.sifa.defs#industryGovernment'

export type { IndustryGovernment }

/** Government & Public Sector. */
const industryGovernment = l.token($nsid, 'industryGovernment')

export { industryGovernment }

/** Healthcare & Life Sciences. */
type IndustryHealthcare = 'id.sifa.defs#industryHealthcare'

export type { IndustryHealthcare }

/** Healthcare & Life Sciences. */
const industryHealthcare = l.token($nsid, 'industryHealthcare')

export { industryHealthcare }

/** Real Estate & Construction. */
type IndustryRealEstate = 'id.sifa.defs#industryRealEstate'

export type { IndustryRealEstate }

/** Real Estate & Construction. */
const industryRealEstate = l.token($nsid, 'industryRealEstate')

export { industryRealEstate }

/** Technology. */
type IndustryTechnology = 'id.sifa.defs#industryTechnology'

export type { IndustryTechnology }

/** Technology. */
const industryTechnology = l.token($nsid, 'industryTechnology')

export { industryTechnology }

/** Project contributor. */
type ProjectContributor = 'id.sifa.defs#projectContributor'

export type { ProjectContributor }

/** Project contributor. */
const projectContributor = l.token($nsid, 'projectContributor')

export { projectContributor }

/** Cybersecurity. */
type DomainCybersecurity = 'id.sifa.defs#domainCybersecurity'

export type { DomainCybersecurity }

/** Cybersecurity. */
const domainCybersecurity = l.token($nsid, 'domainCybersecurity')

export { domainCybersecurity }

/** Fashion Design. */
type DomainFashionDesign = 'id.sifa.defs#domainFashionDesign'

export type { DomainFashionDesign }

/** Fashion Design. */
const domainFashionDesign = l.token($nsid, 'domainFashionDesign')

export { domainFashionDesign }

/** HR & Recruitment. */
type DomainHrRecruitment = 'id.sifa.defs#domainHrRecruitment'

export type { DomainHrRecruitment }

/** HR & Recruitment. */
const domainHrRecruitment = l.token($nsid, 'domainHrRecruitment')

export { domainHrRecruitment }

/** Product & UX Design. */
type DomainProductDesign = 'id.sifa.defs#domainProductDesign'

export type { DomainProductDesign }

/** Product & UX Design. */
const domainProductDesign = l.token($nsid, 'domainProductDesign')

export { domainProductDesign }

/** Travel & Tourism. */
type DomainTravelTourism = 'id.sifa.defs#domainTravelTourism'

export type { DomainTravelTourism }

/** Travel & Tourism. */
const domainTravelTourism = l.token($nsid, 'domainTravelTourism')

export { domainTravelTourism }

/** Agriculture & Food. */
type IndustryAgriculture = 'id.sifa.defs#industryAgriculture'

export type { IndustryAgriculture }

/** Agriculture & Food. */
const industryAgriculture = l.token($nsid, 'industryAgriculture')

export { industryAgriculture }

/** Hospitality & Tourism. */
type IndustryHospitality = 'id.sifa.defs#industryHospitality'

export type { IndustryHospitality }

/** Hospitality & Tourism. */
const industryHospitality = l.token($nsid, 'industryHospitality')

export { industryHospitality }

/** Professional working proficiency. */
type ProfessionalWorking = 'id.sifa.defs#professionalWorking'

export type { ProfessionalWorking }

/** Professional working proficiency. */
const professionalWorking = l.token($nsid, 'professionalWorking')

export { professionalWorking }

/** Investment Management. */
type DomainInvestmentMgmt = 'id.sifa.defs#domainInvestmentMgmt'

export type { DomainInvestmentMgmt }

/** Investment Management. */
const domainInvestmentMgmt = l.token($nsid, 'domainInvestmentMgmt')

export { domainInvestmentMgmt }

/** Mobile & Wireless Services. */
type DomainMobileServices = 'id.sifa.defs#domainMobileServices'

export type { DomainMobileServices }

/** Mobile & Wireless Services. */
const domainMobileServices = l.token($nsid, 'domainMobileServices')

export { domainMobileServices }

/** Port & Terminal Operations. */
type DomainPortOperations = 'id.sifa.defs#domainPortOperations'

export type { DomainPortOperations }

/** Port & Terminal Operations. */
const domainPortOperations = l.token($nsid, 'domainPortOperations')

export { domainPortOperations }

/** The category of a related link on a presentation. Open set. */
type PresentationLinkType =
  | 'id.sifa.defs#linkSlides'
  | 'id.sifa.defs#linkRecording'
  | 'id.sifa.defs#linkEvent'
  | 'id.sifa.defs#linkRegistration'
  | 'id.sifa.defs#linkWriteup'
  | 'id.sifa.defs#linkOther'
  | l.UnknownString

export type { PresentationLinkType }

/** The category of a related link on a presentation. Open set. */
const presentationLinkType = l.string<{
  knownValues: [
    'id.sifa.defs#linkSlides',
    'id.sifa.defs#linkRecording',
    'id.sifa.defs#linkEvent',
    'id.sifa.defs#linkRegistration',
    'id.sifa.defs#linkWriteup',
    'id.sifa.defs#linkOther',
  ]
}>()

export { presentationLinkType }

/** Manufacturing & Engineering. */
type IndustryManufacturing = 'id.sifa.defs#industryManufacturing'

export type { IndustryManufacturing }

/** Manufacturing & Engineering. */
const industryManufacturing = l.token($nsid, 'industryManufacturing')

export { industryManufacturing }

/** Clinical Research. */
type DomainClinicalResearch = 'id.sifa.defs#domainClinicalResearch'

export type { DomainClinicalResearch }

/** Clinical Research. */
const domainClinicalResearch = l.token($nsid, 'domainClinicalResearch')

export { domainClinicalResearch }

/** Primary & Secondary Education. */
type DomainPrimarySecondary = 'id.sifa.defs#domainPrimarySecondary'

export type { DomainPrimarySecondary }

/** Primary & Secondary Education. */
const domainPrimarySecondary = l.token($nsid, 'domainPrimarySecondary')

export { domainPrimarySecondary }

/** Naval Architecture & Marine Engineering. */
type DomainNavalArchitecture = 'id.sifa.defs#domainNavalArchitecture'

export type { DomainNavalArchitecture }

/** Naval Architecture & Marine Engineering. */
const domainNavalArchitecture = l.token($nsid, 'domainNavalArchitecture')

export { domainNavalArchitecture }

/** Autonomous Vehicles. */
type DomainAutonomousVehicles = 'id.sifa.defs#domainAutonomousVehicles'

export type { DomainAutonomousVehicles }

/** Autonomous Vehicles. */
const domainAutonomousVehicles = l.token($nsid, 'domainAutonomousVehicles')

export { domainAutonomousVehicles }

/** Software Engineering. */
type DomainSoftwareEngineering = 'id.sifa.defs#domainSoftwareEngineering'

export type { DomainSoftwareEngineering }

/** Software Engineering. */
const domainSoftwareEngineering = l.token($nsid, 'domainSoftwareEngineering')

export { domainSoftwareEngineering }

/** Management Consulting. */
type DomainManagementConsulting = 'id.sifa.defs#domainManagementConsulting'

export type { DomainManagementConsulting }

/** Management Consulting. */
const domainManagementConsulting = l.token($nsid, 'domainManagementConsulting')

export { domainManagementConsulting }

/** Textile Manufacturing. */
type DomainTextileManufacturing = 'id.sifa.defs#domainTextileManufacturing'

export type { DomainTextileManufacturing }

/** Textile Manufacturing. */
const domainTextileManufacturing = l.token($nsid, 'domainTextileManufacturing')

export { domainTextileManufacturing }
