name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  release:
    name: Release
    if: github.repository == 'eurosky-social/eurosky-portal'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      tag_ref: ${{ steps.release.outputs.tag_ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          check-latest: true
          cache: pnpm

      - name: Create pull request for next release, or Publish a new github release and tag
        id: changesets
        uses: changesets/action@v1

        with:
          title: Prepare next release
          createGithubReleases: true
          publish: pnpm release
          version: pnpm version-package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup release variables
        id: release
        run: |
          echo '${{steps.changesets.outputs.publishedPackages}}'
          release_version=$(jq -cr '.[] | select(.name | contains("eurosky-portal")) | .version' <<< '${{ steps.changesets.outputs.publishedPackages }}')
          echo "tag_ref=v${release_version%,}" >> "$GITHUB_OUTPUT"

      - name: Print tag_ref
        if: ${{ steps.changesets.outputs.published == 'true' }}
        run: |
          echo 'tag: ${{ steps.release.outputs.tag_ref }}'

  publish:
    needs: [release]
    name: Publish release
    if: ${{ needs.release.outputs.published == 'true' }}
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
    with:
      tag_ref: ${{ needs.release.outputs.tag_ref }}
